### ISSUE TITLE
smart-type

### ISSUE THREAD

**Issue by edifierx666** [adamwojszczyk/sepia-theme#1]
version:0.3.0
language:javascript
os:macos big sur 11.4

Prompt content is not clear.

![image](https://user-images.githubusercontent.com/39356752/124873473-1a897980-dff9-11eb-9c13-6b0973a83796.png)
![image](https://user-images.githubusercontent.com/39356752/124873629-502e6280-dff9-11eb-9961-40b414bc2da0.png)

**Comment by adamwojszczyk** [comment]
@edifierx666 On linux and windows it looks fine (attached image). IntelliJ calculates the value based on  intellij.theme.json : ui.CompletionPopup.foreground and it looks like it does it differently for mac os. As a workaround you may edit that value in a jar and change it to #000000 then it looks like in IntelliJ Light theme (still brighter than on linux/windows). Write me back if it works for you. We can report it then to Jetbrains, I hope they fix it if not I will consider publishing two themes in a plugin, one with that fix for mac os.
BTW Why your "return" has such background. Does it always look like?

![image](https://user-images.githubusercontent.com/4930054/125177079-5418db00-e1d9-11eb-9597-1d729d9195c4.png)

**Comment by edifierx666** [comment]
Thank you for your help.
I used the plugin Return Highlighter so return would be highlighted.
The theme is very nice.

**Comment by adamwojszczyk** [comment]
@edifierx666 Has the change helped with the problem?

**Comment by edifierx666** [comment]
This is clearer than before
